/**
 * Country name → IANA timezone(s) alias map.
 * Allows users to search by country name instead of needing to know the IANA representative city.
 * Source: IANA Time Zone Database + UN member states.
 */
export const COUNTRY_TO_TIMEZONES: Record<string, string[]> = {
  // Africa
  Algeria: ["Africa/Algiers"],
  Angola: ["Africa/Luanda"],
  Benin: ["Africa/Porto-Novo"],
  Botswana: ["Africa/Gaborone"],
  "Burkina Faso": ["Africa/Ouagadougou"],
  Burundi: ["Africa/Bujumbura"],
  Cameroon: ["Africa/Douala"],
  "Cape Verde": ["Atlantic/Cape_Verde"],
  "Central African Republic": ["Africa/Bangui"],
  Chad: ["Africa/Ndjamena"],
  Comoros: ["Indian/Comoro"],
  Congo: ["Africa/Brazzaville"],
  "Congo, Democratic Republic": ["Africa/Kinshasa", "Africa/Lubumbashi"],
  "Ivory Coast": ["Africa/Abidjan"],
  Djibouti: ["Africa/Djibouti"],
  Egypt: ["Africa/Cairo"],
  "Equatorial Guinea": ["Africa/Malabo"],
  Eritrea: ["Africa/Asmara"],
  Eswatini: ["Africa/Mbabane"],
  Ethiopia: ["Africa/Addis_Ababa"],
  Gabon: ["Africa/Libreville"],
  Gambia: ["Africa/Banjul"],
  Ghana: ["Africa/Accra"],
  Guinea: ["Africa/Conakry"],
  "Guinea-Bissau": ["Africa/Bissau"],
  Kenya: ["Africa/Nairobi"],
  Lesotho: ["Africa/Maseru"],
  Liberia: ["Africa/Monrovia"],
  Libya: ["Africa/Tripoli"],
  Madagascar: ["Indian/Antananarivo"],
  Malawi: ["Africa/Blantyre"],
  Mali: ["Africa/Bamako"],
  Mauritania: ["Africa/Nouakchott"],
  Mauritius: ["Indian/Mauritius"],
  Morocco: ["Africa/Casablanca"],
  Mozambique: ["Africa/Maputo"],
  Namibia: ["Africa/Windhoek"],
  Niger: ["Africa/Niamey"],
  Nigeria: ["Africa/Lagos"],
  Rwanda: ["Africa/Kigali"],
  "Sao Tome and Principe": ["Africa/Sao_Tome"],
  Senegal: ["Africa/Dakar"],
  Seychelles: ["Indian/Mahe"],
  "Sierra Leone": ["Africa/Freetown"],
  Somalia: ["Africa/Mogadishu"],
  "South Africa": ["Africa/Johannesburg"],
  "South Sudan": ["Africa/Juba"],
  Sudan: ["Africa/Khartoum"],
  Tanzania: ["Africa/Dar_es_Salaam"],
  Togo: ["Africa/Lome"],
  Tunisia: ["Africa/Tunis"],
  Uganda: ["Africa/Kampala"],
  Zambia: ["Africa/Lusaka"],
  Zimbabwe: ["Africa/Harare"],
  "Cote d'Ivoire": ["Africa/Abidjan"],
  "Democratic Republic of the Congo": ["Africa/Kinshasa", "Africa/Lubumbashi"],
  "Republic of the Congo": ["Africa/Brazzaville"],
  Swaziland: ["Africa/Mbabane"],
  Zaire: ["Africa/Kinshasa"],

  // Asia
  Afghanistan: ["Asia/Kabul"],
  Armenia: ["Asia/Yerevan"],
  Azerbaijan: ["Asia/Baku"],
  Bahrain: ["Asia/Bahrain"],
  Bangladesh: ["Asia/Dhaka"],
  Bhutan: ["Asia/Thimphu"],
  Brunei: ["Asia/Brunei"],
  Cambodia: ["Asia/Phnom_Penh"],
  China: ["Asia/Shanghai"],
  Cyprus: ["Asia/Nicosia"],
  Georgia: ["Asia/Tbilisi"],
  HongKong: ["Asia/Hong_Kong"],
  "Hong Kong": ["Asia/Hong_Kong"],
  India: ["Asia/Kolkata"],
  Indonesia: ["Asia/Jakarta", "Asia/Makassar", "Asia/Jayapura"],
  Iran: ["Asia/Tehran"],
  Iraq: ["Asia/Baghdad"],
  Israel: ["Asia/Jerusalem"],
  Japan: ["Asia/Tokyo"],
  Jordan: ["Asia/Amman"],
  Kazakhstan: ["Asia/Almaty", "Asia/Aqtau", "Asia/Aqtobe", "Asia/Oral", "Asia/Qyzylorda"],
  Kuwait: ["Asia/Kuwait"],
  Kyrgyzstan: ["Asia/Bishkek"],
  Laos: ["Asia/Vientiane"],
  Lebanon: ["Asia/Beirut"],
  Macau: ["Asia/Macau"],
  Macao: ["Asia/Macau"],
  Malaysia: ["Asia/Kuala_Lumpur", "Asia/Kuching"],
  Maldives: ["Indian/Maldives"],
  Mongolia: ["Asia/Ulaanbaatar", "Asia/Choibalsan", "Asia/Hovd", "Asia/Khandyga"],
  Myanmar: ["Asia/Yangon"],
  Nepal: ["Asia/Kathmandu"],
  "North Korea": ["Asia/Pyongyang"],
  Oman: ["Asia/Muscat"],
  Pakistan: ["Asia/Karachi"],
  Palestine: ["Asia/Gaza", "Asia/Hebron"],
  Philippines: ["Asia/Manila"],
  Qatar: ["Asia/Qatar"],
  "Saudi Arabia": ["Asia/Riyadh"],
  Singapore: ["Asia/Singapore"],
  "South Korea": ["Asia/Seoul"],
  "Sri Lanka": ["Asia/Colombo"],
  Syria: ["Asia/Damascus"],
  Taiwan: ["Asia/Taipei"],
  Tajikistan: ["Asia/Dushanbe"],
  Thailand: ["Asia/Bangkok"],
  "Timor-Leste": ["Asia/Dili"],
  Timor: ["Asia/Dili"],
  Turkey: ["Europe/Istanbul"],
  Turkmenistan: ["Asia/Ashgabat"],
  "United Arab Emirates": ["Asia/Dubai"],
  UAE: ["Asia/Dubai"],
  Uzbekistan: ["Asia/Tashkent", "Asia/Samarkand"],
  Vietnam: ["Asia/Ho_Chi_Minh"],
  Yemen: ["Asia/Aden"],
  "Palestinian Territory": ["Asia/Gaza"],
  "Republic of Korea": ["Asia/Seoul"],
  "Democratic People's Republic of Korea": ["Asia/Pyongyang"],
  "Lao People's Democratic Republic": ["Asia/Vientiane"],
  "State of Palestine": ["Asia/Gaza"],

  // Europe
  Albania: ["Europe/Tirane"],
  Andorra: ["Europe/Andorra"],
  Austria: ["Europe/Vienna"],
  Belarus: ["Europe/Minsk"],
  Belgium: ["Europe/Brussels"],
  Bosnia: ["Europe/Sarajevo"],
  "Bosnia and Herzegovina": ["Europe/Sarajevo"],
  Bulgaria: ["Europe/Sofia"],
  Croatia: ["Europe/Zagreb"],
  CzechRepublic: ["Europe/Prague"],
  "Czech Republic": ["Europe/Prague"],
  Denmark: ["Europe/Copenhagen"],
  Estonia: ["Europe/Tallinn"],
  Finland: ["Europe/Helsinki"],
  France: ["Europe/Paris"],
  Germany: ["Europe/Berlin"],
  Greece: ["Europe/Athens"],
  Hungary: ["Europe/Budapest"],
  Iceland: ["Atlantic/Reykjavik"],
  Ireland: ["Europe/Dublin"],
  Italy: ["Europe/Rome"],
  Kosovo: ["Europe/Belgrade"],
  Latvia: ["Europe/Riga"],
  Liechtenstein: ["Europe/Vaduz"],
  Lithuania: ["Europe/Vilnius"],
  Luxembourg: ["Europe/Luxembourg"],
  Malta: ["Europe/Malta"],
  Moldova: ["Europe/Chisinau"],
  Monaco: ["Europe/Monaco"],
  Montenegro: ["Europe/Podgorica"],
  Netherlands: ["Europe/Amsterdam"],
  "North Macedonia": ["Europe/Skopje"],
  Norway: ["Europe/Oslo"],
  Poland: ["Europe/Warsaw"],
  Portugal: ["Europe/Lisbon"],
  Romania: ["Europe/Bucharest"],
  Russia: [
    "Europe/Kaliningrad",
    "Europe/Moscow",
    "Europe/Simferopol",
    "Asia/Yekaterinburg",
    "Asia/Omsk",
    "Asia/Krasnoyarsk",
    "Asia/Novosibirsk",
    "Asia/Irkutsk",
    "Asia/Yakutsk",
    "Asia/Vladivostok",
    "Asia/Magadan",
    "Asia/Kamchatka",
  ],
  "Russian Federation": ["Europe/Moscow"],
  Serbia: ["Europe/Belgrade"],
  Slovakia: ["Europe/Bratislava"],
  Slovenia: ["Europe/Ljubljana"],
  Spain: ["Europe/Madrid"],
  Sweden: ["Europe/Stockholm"],
  Switzerland: ["Europe/Zurich"],
  Ukraine: ["Europe/Kiev", "Europe/Simferopol"],
  "United Kingdom": ["Europe/London"],
  UK: ["Europe/London"],
  "Vatican City": ["Europe/Rome"],
  "Holy See": ["Europe/Rome"],
  "Republic of Kosovo": ["Europe/Belgrade"],
  "The Netherlands": ["Europe/Amsterdam"],
  "The United Kingdom": ["Europe/London"],

  // North America
  "Antigua and Barbuda": ["America/Antigua"],
  Bahamas: ["America/Nassau"],
  Barbados: ["America/Barbados"],
  Belize: ["America/Belize"],
  Canada: [
    "America/St_Johns",
    "America/Halifax",
    "America/Winnipeg",
    "America/Edmonton",
    "America/Vancouver",
    "America/Whitehorse",
    "America/Dawson_Creek",
    "America/Atikokan",
  ],
  "Costa Rica": ["America/Costa_Rica"],
  Cuba: ["America/Havana"],
  Dominica: ["America/Dominica"],
  "Dominican Republic": ["America/Santo_Domingo"],
  "El Salvador": ["America/El_Salvador"],
  Grenada: ["America/Grenada"],
  Guatemala: ["America/Guatemala"],
  Haiti: ["America/Port-au-Prince"],
  Honduras: ["America/Tegucigalpa"],
  Jamaica: ["America/Jamaica"],
  Mexico: ["America/Mexico_City", "America/Tijuana", "America/Mazatlan"],
  Nicaragua: ["America/Managua"],
  Panama: ["America/Panama"],
  "Saint Kitts and Nevis": ["America/St_Kitts"],
  "Saint Lucia": ["America/St_Lucia"],
  "Saint Vincent and the Grenadines": ["America/St_Vincent"],
  "Trinidad and Tobago": ["America/Port_of_Spain"],
  "United States": [
    "America/New_York",
    "America/Chicago",
    "America/Denver",
    "America/Los_Angeles",
    "America/Anchorage",
    "Pacific/Honolulu",
  ],
  "United States of America": [
    "America/New_York",
    "America/Chicago",
    "America/Denver",
    "America/Los_Angeles",
    "America/Anchorage",
    "Pacific/Honolulu",
  ],
  USA: [
    "America/New_York",
    "America/Chicago",
    "America/Denver",
    "America/Los_Angeles",
    "America/Anchorage",
    "Pacific/Honolulu",
  ],
  "U.S.A.": [
    "America/New_York",
    "America/Chicago",
    "America/Denver",
    "America/Los_Angeles",
    "America/Anchorage",
    "Pacific/Honolulu",
  ],
  "Puerto Rico": ["America/Puerto_Rico"],
  "U.S. Virgin Islands": ["America/Virgin"],
  "British Virgin Islands": ["America/Virgin"],
  Greenland: ["America/Godthab", "America/Danmarkshavn"],
  "Saint Martin": ["America/Marigot"],
  "Sint Maarten": ["America/Lower_Princes"],
  Guadeloupe: ["America/Guadeloupe"],
  Martinique: ["America/Martinique"],
  "French Guiana": ["America/Cayenne"],

  // South America
  Argentina: ["America/Argentina/Buenos_Aires", "America/Argentina/La_Rioja"],
  Bolivia: ["America/La_Paz"],
  Brazil: [
    "America/Noronha",
    "America/Belem",
    "America/Fortaleza",
    "America/Recife",
    "America/Sao_Paulo",
    "America/Campo_Grande",
    "America/Cuiaba",
    "America/Porto_Velho",
    "America/Boa_Vista",
    "America/Manaus",
    "America/Eirunepe",
    "America/Rio_Branco",
  ],
  Chile: ["America/Santiago", "Pacific/Easter"],
  Colombia: ["America/Bogota"],
  Ecuador: ["America/Guayaquil"],
  Guyana: ["America/Guyana"],
  Paraguay: ["America/Asuncion"],
  Peru: ["America/Lima"],
  "Saint Pierre and Miquelon": ["America/Miquelon"],
  Suriname: ["America/Paramaribo"],
  Uruguay: ["America/Montevideo"],
  Venezuela: ["America/Caracas"],
  FalklandIslands: ["Atlantic/Stanley"],
  "Falkland Islands": ["Atlantic/Stanley"],
  "South Georgia and the South Sandwich Islands": ["Atlantic/South_Georgia"],
  "French Southern Territories": ["Indian/Kerguelen"],
  BouvetIsland: ["Antarctica/Bouvet"],
  "Bouvet Island": ["Antarctica/Bouvet"],
  "Heard Island and McDonald Islands": ["Indian/Kerguelen"],
  "Heard Island & McDonald Islands": ["Indian/Kerguelen"],

  // Oceania
  Australia: [
    "Australia/Lord_Howe",
    "Australia/Hobart",
    "Australia/Melbourne",
    "Australia/Sydney",
    "Australia/Broken_Hill",
    "Australia/Adelaide",
    "Australia/Darwin",
    "Australia/Perth",
    "Australia/Eucla",
    "Australia/Brisbane",
    "Australia/Lindeman",
    "Australia/LHI",
  ],
  Fiji: ["Pacific/Fiji"],
  "Marshall Islands": ["Pacific/Majuro", "Pacific/Kwajalein"],
  Micronesia: ["Pacific/Pohnpei", "Pacific/Chatham", "Pacific/Guam"],
  Nauru: ["Pacific/Nauru"],
  Palau: ["Pacific/Palau"],
  "Papua New Guinea": ["Pacific/Port_Moresby"],
  Samoa: ["Pacific/Apia"],
  "Solomon Islands": ["Pacific/Guadalcanal"],
  Tonga: ["Pacific/Tongatapu"],
  Tuvalu: ["Pacific/Funafuti"],
  Vanuatu: ["Pacific/Efate"],
  "New Zealand": ["Pacific/Auckland", "Pacific/Chatham"],
  "Cook Islands": ["Pacific/Rarotonga"],
  Kiribati: ["Pacific/Tarawa", "Pacific/Enderbury", "Pacific/Kiritimati"],
  Niue: ["Pacific/Niue"],
  "Norfolk Island": ["Pacific/Norfolk"],
  Tokelau: ["Pacific/Fakaofo"],
  "New Caledonia": ["Pacific/Noumea"],

  // Antarctica
  Antarctica: ["Antarctica/McMurdo", "Antarctica/Casey", "Antarctica/Davis"],

  // Common US city aliases
  "New York": ["America/New_York"],
  "Los Angeles": ["America/Los_Angeles"],
  Chicago: ["America/Chicago"],
  Houston: ["America/Chicago"],
  Philadelphia: ["America/New_York"],
  "San Antonio": ["America/Chicago"],
  "San Diego": ["America/Los_Angeles"],
  Dallas: ["America/Chicago"],
  "San Francisco": ["America/Los_Angeles"],
  Seattle: ["America/Los_Angeles"],
  Denver: ["America/Denver"],
  Washington: ["America/New_York"],
  Nashville: ["America/Chicago"],
  Boston: ["America/New_York"],
  Atlanta: ["America/New_York"],
  Miami: ["America/New_York"],
  Phoenix: ["America/Phoenix"],
  LasVegas: ["America/Los_Angeles"],
  "Las Vegas": ["America/Los_Angeles"],
  Portland: ["America/Los_Angeles"],
  Austin: ["America/Chicago"],
  Minneapolis: ["America/Chicago"],
  Honolulu: ["Pacific/Honolulu"],
  Anchorage: ["America/Anchorage"],
  Detroit: ["America/Detroit"],

  // Common non-IANA cities
  Mumbai: ["Asia/Kolkata"],
  Bangalore: ["Asia/Kolkata"],
  "New Delhi": ["Asia/Kolkata"],
  Hyderabad: ["Asia/Kolkata"],
  Chennai: ["Asia/Kolkata"],
  Kolkata: ["Asia/Kolkata"],
  Beijing: ["Asia/Shanghai"],
  Shanghai: ["Asia/Shanghai"],
  Guangzhou: ["Asia/Shanghai"],
  Dubai: ["Asia/Dubai"],
  Istanbul: ["Europe/Istanbul"],
  Manila: ["Asia/Manila"],
  Jakarta: ["Asia/Jakarta"],
  Cairo: ["Africa/Cairo"],
  "Sao Paulo": ["America/Sao_Paulo"],
  "Rio de Janeiro": ["America/Sao_Paulo"],
  Lima: ["America/Lima"],
  Bogota: ["America/Bogota"],
  Santiago: ["America/Santiago"],
  BuenosAires: ["America/Argentina/Buenos_Aires"],
  "Buenos Aires": ["America/Argentina/Buenos_Aires"],
  Moscow: ["Europe/Moscow"],
  "Saint Petersburg": ["Europe/Moscow"],
  "St. Petersburg": ["Europe/Moscow"],
  Bangkok: ["Asia/Bangkok"],
  HoChiMinh: ["Asia/Ho_Chi_Minh"],
  "Ho Chi Minh": ["Asia/Ho_Chi_Minh"],
  "Ho Chi Minh City": ["Asia/Ho_Chi_Minh"],
  "Kuala Lumpur": ["Asia/Kuala_Lumpur"],
  Osaka: ["Asia/Tokyo"],
  Seoul: ["Asia/Seoul"],
  Kabul: ["Asia/Kabul"],
  Karachi: ["Asia/Karachi"],
  Lahore: ["Asia/Karachi"],
  Nairobi: ["Africa/Nairobi"],
  Lagos: ["Africa/Lagos"],
  Accra: ["Africa/Accra"],
  Johannesburg: ["Africa/Johannesburg"],
  "Cape Town": ["Africa/Johannesburg"],
  "Dar es Salaam": ["Africa/Dar_es_Salaam"],
  Kampala: ["Africa/Kampala"],
  Dublin: ["Europe/Dublin"],
  Lisbon: ["Europe/Lisbon"],
  Warsaw: ["Europe/Warsaw"],
  Budapest: ["Europe/Budapest"],
  Vienna: ["Europe/Vienna"],
  Prague: ["Europe/Prague"],
  Barcelona: ["Europe/Madrid"],
  Milan: ["Europe/Rome"],
  Amsterdam: ["Europe/Amsterdam"],
  Brussels: ["Europe/Brussels"],
  Stockholm: ["Europe/Stockholm"],
  Oslo: ["Europe/Oslo"],
  Helsinki: ["Europe/Helsinki"],
  Copenhagen: ["Europe/Copenhagen"],
  "Tel Aviv": ["Asia/Jerusalem"],
  Jeddah: ["Asia/Riyadh"],
  "Abu Dhabi": ["Asia/Dubai"],
  Doha: ["Asia/Qatar"],
  "Kuwait City": ["Asia/Kuwait"],
  Manama: ["Asia/Bahrain"],
  Muscat: ["Asia/Muscat"],
  Tbilisi: ["Asia/Tbilisi"],
  Baku: ["Asia/Baku"],
  Yerevan: ["Asia/Yerevan"],
  Kathmandu: ["Asia/Kathmandu"],
  Colombo: ["Asia/Colombo"],
  Dhaka: ["Asia/Dhaka"],
  Almaty: ["Asia/Almaty"],
  Tashkent: ["Asia/Tashkent"],
  Dushanbe: ["Asia/Dushanbe"],
  Bishkek: ["Asia/Bishkek"],
  Ulaanbaatar: ["Asia/Ulaanbaatar"],
  Medellin: ["America/Bogota"],
  Guayaquil: ["America/Guayaquil"],
  Caracas: ["America/Caracas"],
  "Port of Spain": ["America/Port_of_Spain"],
  Havana: ["America/Havana"],
  "Mexico City": ["America/Mexico_City"],
  Tijuana: ["America/Tijuana"],
  Monterrey: ["America/Monterrey"],
  "Guatemala City": ["America/Guatemala"],
  "San Salvador": ["America/El_Salvador"],
  Tegucigalpa: ["America/Tegucigalpa"],
  Managua: ["America/Managua"],
  "San Jose": ["America/Costa_Rica"],
  Nassau: ["America/Nassau"],
  "Port-au-Prince": ["America/Port-au-Prince"],
  SantoDomingo: ["America/Santo_Domingo"],
  "Santo Domingo": ["America/Santo_Domingo"],
  Georgetown: ["America/Guyana"],
  Paramaribo: ["America/Paramaribo"],
  Montevideo: ["America/Montevideo"],
  Asuncion: ["America/Asuncion"],
  "La Paz": ["America/La_Paz"],
  Sucre: ["America/La_Paz"],
  Reykjavik: ["Atlantic/Reykjavik"],
  Kingston: ["Australia/Hobart", "America/Jamaica"],
  Noumea: ["Pacific/Noumea"],
  Nadi: ["Pacific/Fiji"],
  Apia: ["Pacific/Apia"],
  "Nuku'alofa": ["Pacific/Tongatapu"],
  Funafuti: ["Pacific/Funafuti"],
  Tarawa: ["Pacific/Tarawa"],
  Majuro: ["Pacific/Majuro"],
  "Port Vila": ["Pacific/Efate"],
  "Port Moresby": ["Pacific/Port_Moresby"],
  Honiara: ["Pacific/Guadalcanal"],
  Papeete: ["Pacific/Tahiti"],
  "St. Louis": ["America/Chicago"],
};

/**
 * Normalize a search query: lowercase, trim, collapse whitespace.
 */
function normalize(q: string): string {
  return q.toLowerCase().trim().replace(/\s+/g, " ");
}

/**
 * Find timezone IDs matching a country/city alias query.
 * Returns an array of IANA timezone IDs, or empty if no match.
 */
export function findTimezonesByAlias(query: string): string[] {
  const q = normalize(query);
  if (!q) return [];

  // Direct lookup (fast path)
  if (COUNTRY_TO_TIMEZONES[q]) return COUNTRY_TO_TIMEZONES[q];

  // Partial match: find alias keys that start with or contain the query
  const results: string[] = [];
  for (const [alias, zones] of Object.entries(COUNTRY_TO_TIMEZONES)) {
    if (normalize(alias).includes(q) || q.includes(normalize(alias))) {
      results.push(...zones);
    }
  }

  // Dedupe and return
  return [...new Set(results)];
}
