-- =============================================================================
-- Cohorix Platform — Supabase/Postgres Schema
-- =============================================================================
--
-- This file mirrors the schema that was applied directly to the remote database
-- before the supabase/migrations/ directory existed in this repo. It is kept
-- here so the migration history is reproducible and other developers can run
-- `supabase db reset` locally to bootstrap an empty database.
--
-- DO NOT edit this file. Subsequent schema changes must be added as new
-- timestamped migration files in this directory.

-- Erweiterungen
create extension if not exists pgcrypto;

-- Privates Schema fuer Helper-Funktionen (nicht direkt aufrufbar)
create schema if not exists private;
revoke all on schema private from public, anon;

-- ===========================================================================
-- Enums
-- ===========================================================================
create type public.platform_role as enum ('admin', 'moderator');

create type public.voyage_status as enum (
  'planning', 'applications_open', 'review', 'matching',
  'active', 'completed', 'archived'
);

create type public.application_status as enum (
  'draft', 'submitted', 'under_review', 'accepted', 'rejected', 'withdrawn'
);

create type public.enrollment_status as enum (
  'invited', 'active', 'inactive', 'completed', 'withdrawn'
);

create type public.participant_role as enum (
  'frontend', 'backend', 'fullstack', 'design', 'product'
);

create type public.experience_level as enum (
  'beginner', 'intermediate', 'advanced'
);

create type public.team_status as enum (
  'forming', 'active', 'at_risk', 'completed', 'archived'
);

create type public.matching_run_status as enum (
  'queued', 'running', 'completed', 'failed', 'cancelled'
);

create type public.match_proposal_status as enum (
  'suggested', 'confirmed', 'rejected'
);

create type public.onboarding_progress_status as enum (
  'not_started', 'in_progress', 'completed', 'waived'
);

create type public.announcement_status as enum (
  'draft', 'published', 'archived'
);

create type public.audience_kind as enum (
  'all', 'applicants', 'participants', 'team'
);

create type public.calendar_event_type as enum (
  'deadline', 'meeting', 'milestone', 'social', 'demo'
);

create type public.form_status as enum (
  'draft', 'collecting', 'closed', 'archived'
);

create type public.notification_type as enum (
  'application_submitted', 'application_decided', 'team_assigned',
  'onboarding_reminder', 'announcement_published', 'event_changed'
);

-- ===========================================================================
-- Tabellen
-- ===========================================================================

create table public.profiles (
  id uuid primary key references auth.users (id) on delete cascade,
  full_name text not null check (char_length(trim(full_name)) between 2 and 120),
  avatar_path text,
  bio text not null default '',
  timezone text not null default 'UTC',
  github_url text,
  portfolio_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.user_roles (
  user_id uuid not null references public.profiles (id) on delete cascade,
  role public.platform_role not null,
  granted_by uuid references public.profiles (id) on delete set null,
  granted_at timestamptz not null default now(),
  primary key (user_id, role)
);

create table public.skills (
  id bigint generated always as identity primary key,
  slug text not null unique check (slug = lower(slug)),
  name text not null unique,
  active boolean not null default true
);

create table public.profile_skills (
  profile_id uuid not null references public.profiles (id) on delete cascade,
  skill_id bigint not null references public.skills (id) on delete restrict,
  primary key (profile_id, skill_id)
);

create table public.voyages (
  id uuid primary key default gen_random_uuid(),
  number integer not null unique check (number > 0),
  name text not null,
  description text not null default '',
  status public.voyage_status not null default 'planning',
  applications_open_at timestamptz,
  application_deadline timestamptz,
  starts_at timestamptz not null,
  ends_at timestamptz not null,
  min_team_size smallint not null default 4 check (min_team_size > 0),
  max_team_size smallint not null default 6 check (max_team_size >= min_team_size),
  created_by uuid references public.profiles (id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint voyages_date_order check (
    ends_at > starts_at
    and (application_deadline is null or application_deadline <= starts_at)
    and (applications_open_at is null or application_deadline is null or applications_open_at < application_deadline)
  )
);

create table public.applications (
  id uuid primary key default gen_random_uuid(),
  voyage_id uuid not null references public.voyages (id) on delete restrict,
  applicant_id uuid not null references public.profiles (id) on delete restrict,
  status public.application_status not null default 'draft',
  preferred_role public.participant_role,
  experience public.experience_level,
  years_experience numeric(4,1) check (years_experience is null or years_experience >= 0),
  weekly_hours smallint check (weekly_hours is null or weekly_hours between 1 and 80),
  timezone text,
  bio_snapshot text,
  motivation text,
  portfolio_url_snapshot text,
  review_notes text,
  submitted_at timestamptz,
  decided_at timestamptz,
  decided_by uuid references public.profiles (id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (voyage_id, applicant_id),
  constraint applications_submission_fields check (
    status = 'draft'
    or (
      preferred_role is not null and experience is not null
      and weekly_hours is not null and timezone is not null
      and nullif(trim(coalesce(motivation, '')), '') is not null
      and submitted_at is not null
    )
  ),
  constraint applications_decision_fields check (
    status not in ('accepted', 'rejected')
    or (decided_at is not null and decided_by is not null)
  )
);

create table public.application_skills (
  application_id uuid not null references public.applications (id) on delete cascade,
  skill_id bigint not null references public.skills (id) on delete restrict,
  primary key (application_id, skill_id)
);

create table public.application_status_history (
  id bigint generated always as identity primary key,
  application_id uuid not null references public.applications (id) on delete cascade,
  from_status public.application_status,
  to_status public.application_status not null,
  changed_by uuid references public.profiles (id) on delete set null,
  note text,
  created_at timestamptz not null default now()
);

create table public.enrollments (
  id uuid primary key default gen_random_uuid(),
  voyage_id uuid not null references public.voyages (id) on delete restrict,
  account_id uuid not null references public.profiles (id) on delete restrict,
  application_id uuid not null unique references public.applications (id) on delete restrict,
  status public.enrollment_status not null default 'invited',
  participant_role public.participant_role not null,
  experience public.experience_level not null,
  weekly_hours smallint not null check (weekly_hours between 1 and 80),
  timezone text not null,
  joined_at timestamptz,
  completed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (voyage_id, account_id)
);

create table public.availability_windows (
  id bigint generated always as identity primary key,
  enrollment_id uuid not null references public.enrollments (id) on delete cascade,
  weekday smallint not null check (weekday between 1 and 7),
  starts_at time not null,
  ends_at time not null,
  created_at timestamptz not null default now(),
  constraint availability_window_order check (ends_at > starts_at),
  unique (enrollment_id, weekday, starts_at, ends_at)
);

create table public.teams (
  id uuid primary key default gen_random_uuid(),
  voyage_id uuid not null references public.voyages (id) on delete restrict,
  name text not null,
  description text not null default '',
  status public.team_status not null default 'forming',
  mentor_account_id uuid references public.profiles (id) on delete set null,
  created_by uuid references public.profiles (id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (voyage_id, name)
);

create table public.team_memberships (
  id uuid primary key default gen_random_uuid(),
  team_id uuid not null references public.teams (id) on delete restrict,
  enrollment_id uuid not null references public.enrollments (id) on delete restrict,
  team_role public.participant_role not null,
  is_lead boolean not null default false,
  joined_at timestamptz not null default now(),
  left_at timestamptz,
  left_reason text,
  created_by uuid references public.profiles (id) on delete set null,
  constraint team_membership_date_order check (left_at is null or left_at >= joined_at)
);

create unique index team_memberships_one_open_per_enrollment_idx
  on public.team_memberships (enrollment_id) where left_at is null;

create unique index team_memberships_one_open_team_record_idx
  on public.team_memberships (team_id, enrollment_id) where left_at is null;

create table public.onboarding_steps (
  id uuid primary key default gen_random_uuid(),
  voyage_id uuid not null references public.voyages (id) on delete cascade,
  title text not null,
  description text not null default '',
  position smallint not null check (position > 0),
  required boolean not null default true,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (voyage_id, position)
);

create table public.onboarding_progress (
  enrollment_id uuid not null references public.enrollments (id) on delete cascade,
  step_id uuid not null references public.onboarding_steps (id) on delete cascade,
  status public.onboarding_progress_status not null default 'not_started',
  completed_at timestamptz,
  completed_by uuid references public.profiles (id) on delete set null,
  note text,
  updated_at timestamptz not null default now(),
  primary key (enrollment_id, step_id),
  constraint onboarding_completion_fields check (
    status not in ('completed', 'waived') or completed_at is not null
  )
);

create table public.matching_rule_sets (
  id uuid primary key default gen_random_uuid(),
  voyage_id uuid not null references public.voyages (id) on delete cascade,
  name text not null,
  version integer not null check (version > 0),
  active boolean not null default false,
  created_by uuid references public.profiles (id) on delete set null,
  created_at timestamptz not null default now(),
  unique (voyage_id, version)
);

create unique index matching_rule_sets_one_active_idx
  on public.matching_rule_sets (voyage_id) where active;

create table public.matching_rules (
  id uuid primary key default gen_random_uuid(),
  rule_set_id uuid not null references public.matching_rule_sets (id) on delete cascade,
  rule_key text not null,
  weight numeric(5,2) not null check (weight between 0 and 100),
  enabled boolean not null default true,
  config jsonb not null default '{}'::jsonb,
  unique (rule_set_id, rule_key)
);

create table public.matching_runs (
  id uuid primary key default gen_random_uuid(),
  voyage_id uuid not null references public.voyages (id) on delete restrict,
  rule_set_id uuid not null references public.matching_rule_sets (id) on delete restrict,
  status public.matching_run_status not null default 'queued',
  requested_by uuid references public.profiles (id) on delete set null,
  started_at timestamptz,
  finished_at timestamptz,
  error_message text,
  created_at timestamptz not null default now()
);

create table public.match_proposals (
  id uuid primary key default gen_random_uuid(),
  matching_run_id uuid references public.matching_runs (id) on delete cascade,
  voyage_id uuid not null references public.voyages (id) on delete restrict,
  proposed_name text not null,
  status public.match_proposal_status not null default 'suggested',
  compatibility_score numeric(5,2) not null check (compatibility_score between 0 and 100),
  score_breakdown jsonb not null default '{}'::jsonb,
  rationale text not null default '',
  confirmed_team_id uuid unique references public.teams (id) on delete set null,
  decided_by uuid references public.profiles (id) on delete set null,
  decided_at timestamptz,
  created_at timestamptz not null default now()
);

create table public.match_proposal_members (
  proposal_id uuid not null references public.match_proposals (id) on delete cascade,
  enrollment_id uuid not null references public.enrollments (id) on delete restrict,
  proposed_role public.participant_role not null,
  contribution_score numeric(5,2) check (contribution_score between 0 and 100),
  primary key (proposal_id, enrollment_id)
);

create table public.announcements (
  id uuid primary key default gen_random_uuid(),
  voyage_id uuid references public.voyages (id) on delete cascade,
  team_id uuid references public.teams (id) on delete cascade,
  author_id uuid references public.profiles (id) on delete set null,
  title text not null,
  content text not null,
  audience public.audience_kind not null,
  status public.announcement_status not null default 'draft',
  pinned boolean not null default false,
  published_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint announcements_team_audience check (
    (audience = 'team' and team_id is not null)
    or (audience <> 'team' and team_id is null)
  ),
  constraint announcements_published_at check (
    status <> 'published' or published_at is not null
  )
);

create table public.calendar_events (
  id uuid primary key default gen_random_uuid(),
  voyage_id uuid not null references public.voyages (id) on delete cascade,
  team_id uuid references public.teams (id) on delete cascade,
  created_by uuid references public.profiles (id) on delete set null,
  title text not null,
  description text not null default '',
  event_type public.calendar_event_type not null,
  audience public.audience_kind not null default 'participants',
  starts_at timestamptz not null,
  ends_at timestamptz not null,
  all_day boolean not null default false,
  pinned boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint calendar_event_date_order check (ends_at > starts_at),
  constraint calendar_event_team_audience check (
    (audience = 'team' and team_id is not null)
    or (audience <> 'team' and team_id is null)
  )
);

create table public.calendar_event_attendees (
  event_id uuid not null references public.calendar_events (id) on delete cascade,
  account_id uuid not null references public.profiles (id) on delete cascade,
  response text not null default 'pending'
    check (response in ('pending', 'accepted', 'declined', 'tentative')),
  responded_at timestamptz,
  primary key (event_id, account_id)
);

create table public.forms (
  id uuid primary key default gen_random_uuid(),
  voyage_id uuid references public.voyages (id) on delete cascade,
  title text not null,
  description text not null default '',
  status public.form_status not null default 'draft',
  audience public.audience_kind not null default 'participants',
  created_by uuid references public.profiles (id) on delete set null,
  opens_at timestamptz,
  closes_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint forms_date_order check (
    closes_at is null or opens_at is null or closes_at > opens_at
  )
);

create table public.form_questions (
  id uuid primary key default gen_random_uuid(),
  form_id uuid not null references public.forms (id) on delete cascade,
  position smallint not null check (position > 0),
  question_type text not null check (question_type in (
    'short_text', 'long_text', 'number', 'boolean',
    'single_choice', 'multiple_choice', 'date'
  )),
  label text not null,
  description text not null default '',
  required boolean not null default false,
  options jsonb,
  unique (form_id, position)
);

create table public.form_submissions (
  id uuid primary key default gen_random_uuid(),
  form_id uuid not null references public.forms (id) on delete cascade,
  account_id uuid not null references public.profiles (id) on delete cascade,
  submitted_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (form_id, account_id)
);

create table public.form_answers (
  submission_id uuid not null references public.form_submissions (id) on delete cascade,
  question_id uuid not null references public.form_questions (id) on delete cascade,
  value jsonb not null,
  primary key (submission_id, question_id)
);

create table public.notifications (
  id uuid primary key default gen_random_uuid(),
  account_id uuid not null references public.profiles (id) on delete cascade,
  notification_type public.notification_type not null,
  title text not null,
  body text not null,
  data jsonb not null default '{}'::jsonb,
  read_at timestamptz,
  created_at timestamptz not null default now()
);

create table public.audit_log (
  id bigint generated always as identity primary key,
  actor_id uuid references public.profiles (id) on delete set null,
  action text not null,
  entity_type text not null,
  entity_id text not null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

-- ===========================================================================
-- Indizes fuer haeufige Server-Component-Abfragen
-- ===========================================================================

create index profile_skills_skill_id_idx on public.profile_skills (skill_id);
create index applications_applicant_id_idx on public.applications (applicant_id);
create index applications_voyage_status_created_idx on public.applications (voyage_id, status, created_at desc);
create index application_skills_skill_id_idx on public.application_skills (skill_id);
create index application_status_history_application_created_idx on public.application_status_history (application_id, created_at desc);
create index enrollments_account_id_idx on public.enrollments (account_id);
create index enrollments_voyage_status_idx on public.enrollments (voyage_id, status);
create index availability_windows_enrollment_idx on public.availability_windows (enrollment_id);
create index teams_voyage_status_idx on public.teams (voyage_id, status);
create index team_memberships_team_open_idx on public.team_memberships (team_id) where left_at is null;
create index onboarding_steps_voyage_idx on public.onboarding_steps (voyage_id, position);
create index onboarding_progress_step_id_idx on public.onboarding_progress (step_id);
create index matching_rules_rule_set_id_idx on public.matching_rules (rule_set_id);
create index matching_runs_voyage_created_idx on public.matching_runs (voyage_id, created_at desc);
create index match_proposals_voyage_status_idx on public.match_proposals (voyage_id, status);
create index match_proposal_members_enrollment_id_idx on public.match_proposal_members (enrollment_id);
create index announcements_voyage_status_published_idx on public.announcements (voyage_id, status, published_at desc);
create index calendar_events_voyage_starts_idx on public.calendar_events (voyage_id, starts_at);
create index calendar_event_attendees_account_idx on public.calendar_event_attendees (account_id, event_id);
create index forms_voyage_status_idx on public.forms (voyage_id, status);
create index form_questions_form_idx on public.form_questions (form_id, position);
create index form_submissions_account_idx on public.form_submissions (account_id, form_id);
create index form_answers_question_id_idx on public.form_answers (question_id);
create index notifications_unread_account_idx on public.notifications (account_id, created_at desc) where read_at is null;
create index audit_log_entity_idx on public.audit_log (entity_type, entity_id, created_at desc);
create index audit_log_actor_idx on public.audit_log (actor_id, created_at desc);

-- ===========================================================================
-- Helper-Funktionen (privates Schema)
-- ===========================================================================

create or replace function private.is_staff()
returns boolean language sql stable security definer set search_path = ''
as $$
  select (select auth.uid()) is not null
    and exists (
      select 1 from public.user_roles ur
      where ur.user_id = (select auth.uid()) and ur.role in ('admin', 'moderator')
    );
$$;

revoke all on function private.is_staff() from public;
grant usage on schema private to authenticated;
grant execute on function private.is_staff() to authenticated;

create or replace function private.owns_enrollment(target_enrollment_id uuid)
returns boolean language sql stable security definer set search_path = ''
as $$
  select (select auth.uid()) is not null
    and exists (
      select 1 from public.enrollments e
      where e.id = target_enrollment_id and e.account_id = (select auth.uid())
    );
$$;

revoke all on function private.owns_enrollment(uuid) from public;
grant execute on function private.owns_enrollment(uuid) to authenticated;

create or replace function private.handle_new_user()
returns trigger language plpgsql security definer set search_path = ''
as $$
declare requested_name text;
begin
  requested_name := trim(coalesce(new.raw_user_meta_data ->> 'full_name', ''));
  if char_length(requested_name) < 2 then requested_name := 'New member'; end if;
  insert into public.profiles (id, full_name) values (new.id, requested_name);
  return new;
end;
$$;

revoke all on function private.handle_new_user() from public, anon, authenticated;

create trigger on_auth_user_created
after insert on auth.users
for each row execute function private.handle_new_user();

create or replace function public.set_updated_at()
returns trigger language plpgsql set search_path = ''
as $$
begin new.updated_at = now(); return new; end;
$$;

create trigger profiles_set_updated_at before update on public.profiles for each row execute function public.set_updated_at();
create trigger voyages_set_updated_at before update on public.voyages for each row execute function public.set_updated_at();
create trigger applications_set_updated_at before update on public.applications for each row execute function public.set_updated_at();
create trigger enrollments_set_updated_at before update on public.enrollments for each row execute function public.set_updated_at();
create trigger teams_set_updated_at before update on public.teams for each row execute function public.set_updated_at();
create trigger onboarding_steps_set_updated_at before update on public.onboarding_steps for each row execute function public.set_updated_at();
create trigger onboarding_progress_set_updated_at before update on public.onboarding_progress for each row execute function public.set_updated_at();
create trigger announcements_set_updated_at before update on public.announcements for each row execute function public.set_updated_at();
create trigger calendar_events_set_updated_at before update on public.calendar_events for each row execute function public.set_updated_at();
create trigger forms_set_updated_at before update on public.forms for each row execute function public.set_updated_at();
create trigger form_submissions_set_updated_at before update on public.form_submissions for each row execute function public.set_updated_at();

-- ===========================================================================
-- Row Level Security (RLS)
-- ===========================================================================
alter table public.profiles enable row level security;
alter table public.user_roles enable row level security;
alter table public.skills enable row level security;
alter table public.profile_skills enable row level security;
alter table public.voyages enable row level security;
alter table public.applications enable row level security;
alter table public.application_skills enable row level security;
alter table public.application_status_history enable row level security;
alter table public.enrollments enable row level security;
alter table public.availability_windows enable row level security;
alter table public.teams enable row level security;
alter table public.team_memberships enable row level security;
alter table public.onboarding_steps enable row level security;
alter table public.onboarding_progress enable row level security;
alter table public.matching_rule_sets enable row level security;
alter table public.matching_rules enable row level security;
alter table public.matching_runs enable row level security;
alter table public.match_proposals enable row level security;
alter table public.match_proposal_members enable row level security;
alter table public.announcements enable row level security;
alter table public.calendar_events enable row level security;
alter table public.calendar_event_attendees enable row level security;
alter table public.forms enable row level security;
alter table public.form_questions enable row level security;
alter table public.form_submissions enable row level security;
alter table public.form_answers enable row level security;
alter table public.notifications enable row level security;
alter table public.audit_log enable row level security;

create policy profiles_select_own_or_staff
on public.profiles for select to authenticated
using ((select auth.uid()) = id or (select private.is_staff()));

create policy profiles_update_own
on public.profiles for update to authenticated
using ((select auth.uid()) = id)
with check ((select auth.uid()) = id);

create policy skills_select_authenticated
on public.skills for select to authenticated
using (active or (select private.is_staff()));

create policy voyages_select_authenticated
on public.voyages for select to authenticated
using (true);

create policy applications_select_own_or_staff
on public.applications for select to authenticated
using (applicant_id = (select auth.uid()) or (select private.is_staff()));

create policy applications_insert_own_draft
on public.applications for insert to authenticated
with check (applicant_id = (select auth.uid()) and status = 'draft');

create policy applications_update_own_draft
on public.applications for update to authenticated
using (applicant_id = (select auth.uid()) and status = 'draft')
with check (applicant_id = (select auth.uid()) and status in ('draft', 'submitted'));

create policy enrollments_select_own_or_staff
on public.enrollments for select to authenticated
using (account_id = (select auth.uid()) or (select private.is_staff()));

create policy availability_windows_own_or_staff
on public.availability_windows for all to authenticated
using ((select private.owns_enrollment(enrollment_id)) or (select private.is_staff()))
with check ((select private.owns_enrollment(enrollment_id)) or (select private.is_staff()));

create policy onboarding_progress_select_own_or_staff
on public.onboarding_progress for select to authenticated
using ((select private.owns_enrollment(enrollment_id)) or (select private.is_staff()));

create policy onboarding_progress_update_own_or_staff
on public.onboarding_progress for update to authenticated
using ((select private.owns_enrollment(enrollment_id)) or (select private.is_staff()))
with check ((select private.owns_enrollment(enrollment_id)) or (select private.is_staff()));

create policy notifications_select_own
on public.notifications for select to authenticated
using (account_id = (select auth.uid()));

create policy notifications_update_own
on public.notifications for update to authenticated
using (account_id = (select auth.uid()))
with check (account_id = (select auth.uid()));

create policy staff_read_user_roles
on public.user_roles for select to authenticated
using ((select private.is_staff()));

create policy staff_read_audit_log
on public.audit_log for select to authenticated
using ((select private.is_staff()));

-- ===========================================================================
-- Grants fuer Supabase Data API
-- ===========================================================================
grant select, update on public.profiles to authenticated;
grant select on public.skills to authenticated;
grant select on public.voyages to authenticated;
grant select, insert, update on public.applications to authenticated;
grant select on public.enrollments to authenticated;
grant select, insert, update, delete on public.availability_windows to authenticated;
grant select, update on public.onboarding_progress to authenticated;
grant select, update on public.notifications to authenticated;
grant select on public.user_roles to authenticated;
grant select on public.audit_log to authenticated;
